version: '3.8'

services:
    # Reverse proxy using Caddy to route traffic to containers.
    # See Caddyfile to configure subdomains to each container.       
    reverse-proxy:
        image: caddy/caddy:2-alpine
        container_name: reverse-proxy
        restart: unless-stopped
        # network_mode: "host"
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - caddy_data:/data
          - caddy_config:/config
          - $PWD/Caddyfile:/etc/caddy/Caddyfile
          - $PWD/certs:/data/certs
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # All Other Containers -- For Demo Purposes

    test:
      image: containous/whoami:latest
      container_name: test
      restart: unless-stopped
      environment:
        WHOAMI_NAME: fake-app

volumes:
  caddy_data:
  caddy_config:
